### PR TITLE
Remove unused lines in initialize.py

### PR DESCRIPTION
**Pull request by vlad-perevezentsev**

### CODE REVIEW

**Comment by PokhodenkoSA** [comment]
@vlad-perevezentsev Could you please explain what you want to achieve with this modifications and why did you do it in this way?

**Comment by PokhodenkoSA** [comment]
Name of the PR does not follow the content of PR.

**Comment by reazulhoque** [comment]
Let us postpone this until the next release.

**Comment by PokhodenkoSA** [comment]
Do not know the reason of this. Reopen if needed.

**Pull request closed without merging**
