### PR TITLE
Port existing functions enabled through dpnp

### PR DESCRIPTION
**Pull request by reazulhoque**
This PR ports the implementation of functions through dpnp using the new approach. It cleans up the older approach as well.

### CODE REVIEW

**Comment by diptorupd** [comment]
@PokhodenkoSA can you please see why CI is failing for this PR?

**Comment by PokhodenkoSA** [comment]
> why CI is failing for this PR

Tests failed on Linux:
- `test_dppy_fallback_reductions`
- `test_rename_ndarray`

Windows fails because of CI internal problem.

**Comment by reazulhoque** [comment]
1. test_dppy_fallback_reductions fails as it was using np.amax() as a reduction kernel. I have now updated the test to use prange as a reduction kernel.
2. I can not reproduce it locally.

**Comment by reazulhoque** [comment]
Tested with the following dependencies locally:

dpctl: d157ee0b1a9ba88d0f3b226bd069af2dd9a56b9a
Numba (patched): 864790061aa7548ac2b7ebcf448354def849e657
dpnp: 0.4.0

Result:

```
----------------------------------------------------------------------
Ran 157 tests in 70.398s
OK (skipped=2, expected failures=1)
```

**Review by PokhodenkoSA — APPROVED** [review]
LGTM

**Pull request merged**
