### PR TITLE
Implement NumPy functions `trace` and `diagonal` via DPNP

### PR DESCRIPTION
**Pull request by Rubtsowa**
Add support for DPNP functions: trace and diagonal.

### CODE REVIEW

**Comment by PokhodenkoSA** [comment]
CI fails because there is no DPNP package on Windows. Please protect test run as in other tests.

**Review by PokhodenkoSA — CHANGES_REQUESTED** [review]
Please, fix CI.

**Comment by diptorupd** [comment]
@Rubtsowa please add description to your PR. A PR without any description is a very hard to understand and just the title is not enough. Please describe in detail the changes, reason for changes, and expected outcome of the PR.

**Comment by PokhodenkoSA** [comment]
Hi @diptorupd. Let me introduce you. PRs marked as `dpnp` label are related to DPNP integration. This PR is for untegrate with new DPNP functions `trace` and `diagonal`.
There is also meta issue with a list and progress about new function integration - #383.

**Review by PokhodenkoSA — APPROVED** [review]
Code cleaning in separate PR.

**Pull request merged**
