### PR TITLE
Fix the flag in "subprocess.check_call" for Windows

### PR DESCRIPTION
**Pull request by vlad-perevezentsev**
This PR fixes Bandit warning in building script related to `subprocess.check_call(..., shell=True)`.

### CODE REVIEW

**Review by diptorupd — APPROVED** [review]

**Comment by PokhodenkoSA** [comment]
@vlad-perevezentsev could you please investigate Windows CI fail?
I have merged main into this PR branch. It should work.

**Review by PokhodenkoSA — CHANGES_REQUESTED** [review]
@vlad-perevezentsev could you please investigate Windows CI fail?
I have merged main into this PR branch. It should work.
It seems that some service fails. @xaleryb could you check please?

**Comment by PokhodenkoSA** [comment]
Need to restart CI.

**Review by PokhodenkoSA — APPROVED** [review]
LGTM

**Pull request merged**
