### PR TITLE
Change black to only allow 80 char lines. Reformat sources.

### PR DESCRIPTION
**Pull request by diptorupd**
Use a consistent black formatting style across dpctl and numba-dppy.

### CODE REVIEW

**Comment by diptorupd** [comment]
The changes need to be merged and not squashed.

**Comment by PokhodenkoSA** [comment]
@diptorupd please move coverage changes to separate PR.
About line width - OK. But now is not a good time for this. CI does not work. As I understand you made it automatically. Could you please repeat it later when CI will work again?

**Comment by diptorupd** [comment]
> @diptorupd please move coverage changes to separate PR. About line width - OK. But now is not a good time for this. CI does not work. As I understand you made it automatically. Could you please repeat it later when CI will work again?

I can move out the coverage changes to a separate PR, but is just more overhead. As you can see, I want to merge the PR that will preserve the coverage changes as a separate commit.

I do not follow your argument about the CI. Why should a formatting change have anything to do with CI? Moreover, I can see that the public jobs ran successfully. If we wait for internal CI, then unfortunately we have to stop developing and that is unacceptable to me.

**Comment by diptorupd** [comment]
I am closing the PR for now. Instead of doing the refactoring for code improvements in this manner, I have decided to develop the changes in my own branch on my fork. It helps me as the changes are incremental and one on top of the other. Once CI is back, I will take the individual commits from my branch and open PRs.

**Pull request closed without merging**
