### PR TITLE
Load dpctl lib on Linux using `libDPCTLSyclInterface.so.0`

### LINKED ISSUE #700: Crash in `DPCTLQueue_SubmitRange` when use `dpctl 0.12.0dev2` or `dpctl 0.12.0dev3`
Test: test_dpnp_interacting_with_parfor

```gdb
(gdb) bt
#0  0x00007fffd88fb11e in zeKernelSetArgumentValue () from /lib/x86_64-linux-gnu/libze_intel_gpu.so.1
#1  0x00007fffddbc3a64 in piKernelSetArg ()
   from /localdisk/work/spokhode/miniconda3/envs/idev/lib/python3.9/site-packages/dpctl/../../../libpi_level_zero.so
#2  0x00007fffde1fe06f in cl::sycl::detail::SetKernelParamsAndLaunch(std::shared_ptr<cl::sycl::detail::queue_impl> const&, std::vector<cl::sycl::detail::ArgDesc, std::allocator<cl::sycl::detail::ArgDesc> >&, std::shared_ptr<cl::sycl::detail::device_image_impl> const&, _pi_kernel*, cl::sycl::detail::NDRDescT&, std::vector<_pi_event*, std::allocator<_pi_event*> >&, _pi_event**, std::vector<bool, std::allocator<bool> > const&, std::function<void* (cl::sycl::detail::AccessorImplHost*)> const&)::$_6::operator()(cl::sycl::detail::ArgDesc&, unsigned long) const ()
   from /localdisk/work/spokhode/miniconda3/envs/idev/lib/python3.9/site-packages/dpctl/../../../libsycl.so.5
#3  0x00007fffde1f63ef in cl::sycl::detail::SetKernelParamsAndLaunch(std::shared_ptr<cl::sycl::detail::queue_impl> const&, std::vector<cl::sycl::detail::ArgDesc, std::allocator<cl::sycl::detail::ArgDesc> >&, std::shared_ptr<cl::sycl::detail::device_image_impl> const&, _pi_kernel*, cl::sycl::detail::NDRDescT&, std::vector<_pi_event*, std::allocator<_pi_event*> >&, _pi_event**, std::vector<bool, std::allocator<bool> > const&, std::function<void* (cl::sycl::detail::AccessorImplHost*)> const&) ()
   from /localdisk/work/spokhode/miniconda3/envs/idev/lib/python3.9/site-packages/dpctl/../../../libsycl.so.5
#4  0x00007fffde1f4eaf in cl::sycl::detail::enqueueImpKernel(std::shared_ptr<cl::sycl::detail::queue_impl> const&, cl::sycl::detail::NDRDescT&, std::vector<cl::sycl::detail::ArgDesc, std::allocator<cl::sycl::detail::ArgDesc> >&, std::shared_ptr<cl::sycl::detail::kernel_bundle_impl> const&, std::shared_ptr<cl::sycl::detail::kernel_impl> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long const&, std::vector<_pi_event*, std::allocator<_pi_event*> >&, _pi_event**, std::function<void* (cl::sycl::detail::AccessorImplHost*)> const&) ()
--Type <RET> for more, q to quit, c to continue without paging--
   from /localdisk/work/spokhode/miniconda3/envs/idev/lib/python3.9/site-packages/dpctl/../../../libsycl.so.5
#5  0x00007fffde23e8c1 in cl::sycl::handler::finalize() ()
   from /localdisk/work/spokhode/miniconda3/envs/idev/lib/python3.9/site-packages/dpctl/../../../libsycl.so.5
#6  0x00007fffde26b85a in cl::sycl::detail::queue_impl::finalizeHandler(cl::sycl::handler&, cl::sycl::detail::CG::CGTYPE const&, cl::sycl::event&) () from /localdisk/work/spokhode/miniconda3/envs/idev/lib/python3.9/site-packages/dpctl/../../../libsycl.so.5
#7  0x00007fffde26b5ab in cl::sycl::detail::queue_impl::submit_impl(std::function<void (cl::sycl::handler&)> const&, std::shared_ptr<cl::sycl::detail::queue_impl> const&, std::shared_ptr<cl::sycl::detail::queue_impl> const&, std::shared_ptr<cl::sycl::detail::queue_impl> const&, cl::sycl::detail::code_location const&, std::function<void (bool, bool, cl::sycl::event&)> const*) ()
   from /localdisk/work/spokhode/miniconda3/envs/idev/lib/python3.9/site-packages/dpctl/../../../libsycl.so.5
#8  0x00007fffde26abb4 in cl::sycl::detail::queue_impl::submit(std::function<void (cl::sycl::handler&)> const&, std::shared_ptr<cl::sycl::detail::queue_impl> const&, cl::sycl::detail::code_location const&, std::function<void (bool, bool, cl::sycl::event&)> const*) () from /localdisk/work/spokhode/miniconda3/envs/idev/lib/python3.9/site-packages/dpctl/../../../libsycl.so.5
#9  0x00007fffde26ab85 in cl::sycl::queue::submit_impl(std::function<void (cl::sycl::handler&)>, cl::sycl::detail::code_location const&) () from /localdisk/work/spokhode/miniconda3/envs/idev/lib/python3.9/site-packages/dpctl/../../../libsycl.so.5
#10 0x00007fffd84918d8 in DPCTLQueue_SubmitRange ()
   from /localdisk/work/spokhode/miniconda3/envs/idev/lib/python3.9/site-packages/dpctl/libDPCTLSyclInterface.so
#11 0x00007fffefbb55d4 in numba_dppy::tests::test_dpnp_functions::Testdpnp_functions::test_dpnp_interacting_with_parfor::$3clocals$3e::f$241(Array<float, 1, C, mutable, aligned>, Array<float, 1, C, mutable, aligned>) ()
```

### PR DESCRIPTION
**Pull request by PokhodenkoSA**
Fixes #700.
Issue in dpctl: https://github.com/IntelPython/dpctl/issues/777

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
It is great that you pinned the problem to the issue with loading the DPCTLSyclInterface, but the proposed solution is not right. 

We should load `.so` files instead, or why keep the `.so` file otherwise? Can you check if in your layout the .so and .so.0 files are symbolic links, or hard files?

**Comment by oleksandr-pavlyk** [comment]
Thanks for IntelPython/dpctl#777. Once this is fixed, this fix wont be necessary

**Comment by PokhodenkoSA** [comment]
> We should load `.so` files instead, or why keep the `.so` file otherwise?

I think it is normal to pin to `.so.0`. It pins to compatible version like other so libraries do.

**Comment by oleksandr-pavlyk** [comment]
The real reason why the fix works is that it makes `llvm` permanently load the same hard file library that the CPython native extensions open:

```
(dev) [08:49:00 vmlin numba-dppy]$ ldd <elided>/envs/dev/lib/python3.9/site-packages/dpctl/_sycl_queue.cp*
        linux-vdso.so.1 (0x00007ffea0f68000)
        libDPCTLSyclInterface.so.0 => <elided>/envs/dev/lib/python3.9/site-packages/dpctl/libDPCTLSyclInterface.so.0 (0x00007feef9d95000)
        libstdc++.so.6 => <elided>/envs/dev/lib/python3.9/site-packages/dpctl/../../../libstdc++.so.6 (0x00007feef9c20000)
```

The merge fix hard codes the happenstance, but if the `dpctl` native extensions are post processed with `readelf` to relink them to a different hard copy of the library the problem will return. 

The key is to maintain consistency between what shared objects of native extensions link to with what `ll.load_library_permanently` loads. 

For this consistency to be maintained the path to open should be determined dynamically from shared objects of `dpctl` extensions. This determination is best delegated to `dpctl` itself.

**Pull request merged**
