### PR TITLE
Don't create a new copy of a usm shared array data pointers for kernel call.

### PR DESCRIPTION
**Pull request by DrTodd13**
In the code that forms the kernel args, we now look to see if the array type is actually a USM shared type.  If so, we just place the data pointer directly into the kernel arg and so we avoid all the overhead of creating a new USM buffer and copying data there before the kernel and back afterwards.

### CODE REVIEW

**Review by reazulhoque — COMMENTED** [review]
@DrTodd13  This branch needs to merge with main. LGTM after that.

**Comment by PokhodenkoSA** [comment]
Waiting for test cases from @reazulhoque.

**Comment by reazulhoque** [comment]
@PokhodenkoSA This PR is ready for review.

**Comment by akharche** [comment]
test_no_copy_usm_shared faild on Windows

**Review by reazulhoque — APPROVED** [review]

**Pull request merged**
