### PR TITLE
Update dpnp 0.8

### PR DESCRIPTION
**Pull request by PokhodenkoSA**
- [x] API change starting from https://github.com/IntelPython/dpnp/pull/902.
- [x] Update to https://github.com/IntelPython/dpnp/pull/926

@shssf @Alexander-Makaryev @oleksandr-pavlyk 
Please, note changes in https://github.com/IntelPython/numba-dppy/pull/524/files#diff-cd1b3e27f060a681f6c297528940f8c3faa8a26f92f009ecc4532b72e61127b8. It is workaround for DPNP issues.

### CODE REVIEW

**Comment by PokhodenkoSA** [comment]
Fails:
```
numba_dppy/tests/njit_tests/dpnp/test_numpy_array_ops.py::test_unary_ops[opencl:gpu:0-max-int32-10] Segmentation fault (core dumped)
```

**Comment by PokhodenkoSA** [comment]
@shssf @Alexander-Makaryev 
I can not merge it because internal CI fails. It fails because we have dpnp 0.7.1=_35 on internal CI.
Also I can not set dependencies dpnp>=0.8*.
Please, set tag on your repo.

**Comment by Alexander-Makaryev** [comment]
@PokhodenkoSA 
Ok, I created a tag as you asked.

**Comment by Alexander-Makaryev** [comment]
@PokhodenkoSA I think that we have misunderstanding about issues that you met.
Please, look at my comment in corresponding topic https://github.com/IntelPython/dpnp/issues/723#issuecomment-913421073

**Comment by PokhodenkoSA** [comment]
> we have misunderstanding about issues that you met

I agree. I met default behavior of dpnp. I should use DPNP_OUTPUT_DPCTL=1 and unskip tests.

**Comment by PokhodenkoSA** [comment]
@shssf @Alexander-Makaryev
Please, upload dpnp 0.8 on internal channels.

**Comment by Alexander-Makaryev** [comment]
@PokhodenkoSA

> @shssf @Alexander-Makaryev
> Please, upload dpnp 0.8 on internal channels.

As I already said, we will upload new versions after finishing work with previous one. For now it is possible to use ready package from CI or build it from sources.

**Review by 1e-to — APPROVED** [review]

**Pull request merged**
