### PR TITLE
Remove kernel wrapper function

### PR DESCRIPTION
**Pull request by diptorupd**
WIP changes to `target.py` to remove the wrapper function needed for every kernel.

### CODE REVIEW

**Comment by diptorupd** [comment]
@PokhodenkoSA @akharche There are still 19 tests that are failing that I need to fix and then polish up the patch. I will get to it tomorrow my day. You can try it out. I expect basic use cases to work.

**Comment by PokhodenkoSA** [comment]
#412 merged. Please, merge this PR with main.

**Comment by akharche** [comment]
@diptorupd I tested it on nuc05 with neo driver version: https://github.com/intel/compute-runtime/releases/tag/21.22.19967 .  And got core dump:
```
Abort was called at 211 line in file:
../neo/shared/source/kernel/kernel_arg_descriptor.h
Aborted (core dumped)
```

**Comment by diptorupd** [comment]
> @diptorupd I tested it on nuc05 with neo driver version: https://github.com/intel/compute-runtime/releases/tag/21.22.19967 . And got core dump:

@akharche what example were you running on nuc05? It will help me debug if you give me the reproducer.

**Comment by akharche** [comment]
> > @diptorupd I tested it on nuc05 with neo driver version: https://github.com/intel/compute-runtime/releases/tag/21.22.19967 . And got core dump:
> 
> @akharche what example were you running on nuc05? It will help me debug if you give me the reproducer.

Could you please try this reproducer? https://gist.github.com/akharche/2acf121caf2f58a7dd6f1d5074cbc51a

**Comment by diptorupd** [comment]
closing the PR as we implemented an alternative workaround in #432

**Pull request closed without merging**
